# Generated by Django 2.2.10 on 2020-05-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asortiman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cijena_bez_pdv', models.FloatField(default=100)),
                ('cijena_s_pdvom', models.FloatField(default=1.0)),
                ('opis', models.TextField(default='ovo je to')),
                ('popust', models.FloatField(default=0)),
                ('kolicina', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DugPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FormInfoadress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica_adresa', models.CharField(max_length=100)),
                ('adresa_stana', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlavnaKnjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('chategory', models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default='primary', max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='primary', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='izlazni_rac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Izlazni_Racun', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='Firma', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('drzava', django_countries.fields.CountryField(max_length=2)),
                ('porezni_broj', models.IntegerField()),
                ('adresa', models.CharField(max_length=100)),
                ('dugovanje', models.ManyToManyField(to='core.DugPartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('asortiman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Asortiman')),
                ('rok_izvrsenja', models.DateField(blank=True, null=True)),
            ],
            bases=('core.asortiman',),
        ),
        migrations.CreateModel(
            name='ulazni_rac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ulazni_Racun', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ugovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj_ugovora', models.TextField()),
                ('datum_potpisivanja', models.DateField()),
                ('vazenje', models.DateField()),
                ('tip', models.CharField(choices=[('ugovor o djelu', 'Ugovor o djelu'), ('na daljinu', 'Na daljinu'), ('potpisani', 'Potpisani')], default='Ugovor o djelu', max_length=120)),
                ('file_ugovor', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('glavna_knjiga1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id_id_id', to='core.GlavnaKnjiga')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id_id_id2', to='core.Partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('ulazni', 'Ulazni'), ('izlazni', 'Izlazni')], default='Ulazni', max_length=120)),
                ('datum_racuna1', models.DateField()),
                ('rok_otplate1', models.DateField()),
                ('ukupno1', models.FloatField(default=0.0)),
                ('osnovica1', models.FloatField(default=0.0)),
                ('pdv', models.FloatField(default=0.0)),
                ('asortiman', models.ManyToManyField(to='core.Asortiman')),
                ('glavna_knjiga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id', to='core.GlavnaKnjiga')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner_id_id', to='core.Partner')),
                ('racuni_izlazni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.izlazni_rac')),
                ('racuni_ulazni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ulazni_rac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oredered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('promoCode', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('ordered_adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FormInfoadress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komercijala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glavni_komercijalista', models.CharField(max_length=50)),
                ('ugovor', models.ManyToManyField(to='core.Ugovor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Budzet', max_length=50)),
                ('ukupno', models.FloatField(default=0.0)),
                ('troskovi', models.FloatField(default=0.0)),
                ('prihodi', models.FloatField(default=0.0)),
                ('glavna_knjiga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id_id', to='core.GlavnaKnjiga')),
            ],
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
                ('datum_validnosti', models.DateField()),
                ('napomena', models.TextField()),
                ('partner', models.ManyToManyField(to='core.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('asortiman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Asortiman')),
                ('dobavljac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner_id1_id', to='core.Partner')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Kategorija')),
            ],
            bases=('core.asortiman',),
        ),
    ]
