# Generated by Django 2.2.10 on 2020-05-31 11:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sifra', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='cars')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asortiman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cijena_bez_pdv', models.FloatField(default=100)),
                ('cijena_s_pdvom', models.FloatField(default=1.0)),
                ('opis', models.TextField(default='ovo je to')),
                ('popust', models.FloatField(default=0)),
                ('kolicina', models.FloatField(default=0)),
                ('sifra', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DugPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FormInfoadress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica_adresa', models.CharField(max_length=100)),
                ('adresa_stana', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlavnaKnjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('chategory', models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default='primary', max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='primary', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='izlazni_rac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Izlazni_Racun', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='Firma', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('drzava', django_countries.fields.CountryField(max_length=2)),
                ('porezni_broj', models.IntegerField()),
                ('adresa', models.CharField(max_length=100)),
                ('iznos', models.FloatField(default=0.0)),
                ('dugovanje', models.ManyToManyField(blank=True, null=True, to='core.DugPartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ulazni_rac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ulazni_Racun', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ugovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj_ugovora', models.TextField()),
                ('datum_potpisivanja', models.DateField()),
                ('vazenje', models.DateField()),
                ('tip', models.CharField(choices=[('ugovor o djelu', 'Ugovor o djelu'), ('na daljinu', 'Na daljinu'), ('potpisani', 'Potpisani')], default='Ugovor o djelu', max_length=120)),
                ('file_ugovor', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('glavna_knjiga1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id_id_id', to='core.GlavnaKnjiga')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id_id_id2', to='core.Partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('ulazni', 'Ulazni'), ('izlazni', 'Izlazni')], default='Ulazni', max_length=120)),
                ('datum_racuna1', models.DateField()),
                ('rok_otplate1', models.DateField()),
                ('ukupno1', models.FloatField(default=0.0)),
                ('osnovica1', models.FloatField(default=0.0)),
                ('pdv', models.FloatField(default=0.0)),
                ('asortiman', models.ManyToManyField(to='core.Asortiman')),
                ('glavna_knjiga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id', to='core.GlavnaKnjiga')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner_id_id', to='core.Partner')),
                ('racuni_izlazni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.izlazni_rac')),
                ('racuni_ulazni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ulazni_rac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oredered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('promoCode', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('ordered_adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FormInfoadress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nabavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('razlog', models.FileField(upload_to='')),
                ('iznos', models.FloatField(default=0.0)),
                ('partneri', models.ManyToManyField(blank=True, null=True, to='core.Partner')),
                ('racuni', models.ManyToManyField(to='core.Racun')),
                ('s_ugovor', models.ManyToManyField(blank=True, null=True, to='core.Ugovor')),
            ],
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_konta', models.FloatField(default=0.0)),
                ('naziv', models.CharField(default='Konto1', max_length=50)),
                ('glavna_knjiga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id12_id_id', to='core.GlavnaKnjiga')),
            ],
        ),
        migrations.CreateModel(
            name='Komercijala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glavni_komercijalista', models.CharField(max_length=50)),
                ('ugovor', models.ManyToManyField(to='core.Ugovor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Budzet', max_length=50)),
                ('ukupno', models.FloatField(default=0.0)),
                ('troskovi', models.FloatField(default=0.0)),
                ('prihodi', models.FloatField(default=0.0)),
                ('glavna_knjiga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GlavnaKnjiga_id_id_id', to='core.GlavnaKnjiga')),
            ],
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
                ('datum_validnosti', models.DateField()),
                ('napomena', models.TextField()),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avans_id_id_id_id2', to='core.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('asortiman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Asortiman')),
                ('rok_izvrsenja', models.DateField(blank=True, null=True)),
                ('dobavljac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner_id153_id', to='core.Partner')),
            ],
            bases=('core.asortiman',),
        ),
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('asortiman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Asortiman')),
                ('dobavljac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner_id1_id', to='core.Partner')),
                ('kategorija', models.ForeignKey(default='Pocetna', on_delete=django.db.models.deletion.CASCADE, to='core.Kategorija')),
            ],
            bases=('core.asortiman',),
        ),
    ]
