# Generated by Django 2.2.10 on 2020-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asortiman',
            name='kolicina',
            field=models.FloatField(default=1),
        ),
    ]
