# Generated by Django 2.2.10 on 2020-05-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('asortiman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Asortiman')),
                ('rok_izvrsenja', models.DateField()),
                ('sati', models.FloatField(default=0)),
            ],
            bases=('core.asortiman',),
        ),
        migrations.AddField(
            model_name='artikal',
            name='kolicina',
            field=models.FloatField(default=0),
        ),
    ]
