# Generated by Django 2.2.10 on 2020-05-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avans',
            name='partner',
        ),
        migrations.AddField(
            model_name='avans',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avans_id_id_id_id2', to='core.Partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='dugovanje',
            field=models.ManyToManyField(blank=True, null=True, to='core.DugPartner'),
        ),
    ]
