# Generated by Django 2.2.10 on 2020-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200515_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='pdv',
            field=models.FloatField(default=0.0),
        ),
    ]
