# Generated by Django 2.2.10 on 2020-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200516_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='rok_izvrsenja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
