# Generated by Django 2.2.10 on 2020-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200517_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='DugPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='artikal',
            name='dobavljac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner_id1_id', to='core.Partner'),
        ),
        migrations.AddField(
            model_name='ugovor',
            name='tip',
            field=models.CharField(choices=[('ugovor o djelu', 'Ugovor o djelu'), ('na daljinu', 'Na daljinu'), ('potpisani', 'Potpisani')], default='Ugovor o djelu', max_length=120),
        ),
        migrations.AddField(
            model_name='partner',
            name='dugovanje',
            field=models.ManyToManyField(to='core.DugPartner'),
        ),
    ]
