# Generated by Django 2.2.10 on 2020-05-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_konto'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ukupno_dug',
            field=models.FloatField(default=0.0),
        ),
    ]
