# Generated by Django 2.2.10 on 2020-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200516_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='osnovica',
            field=models.FloatField(default=0.0),
        ),
    ]
