# Generated by Django 2.2.10 on 2020-05-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200521_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
                ('datum_validnosti', models.DateField()),
                ('napomena', models.TextField()),
                ('partner', models.ManyToManyField(to='core.Partner')),
            ],
        ),
    ]
