# Generated by Django 2.2.10 on 2020-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blagajna_obavijesti_projekti_tenderi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transakcije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.CharField(max_length=10)),
                ('posiljalac', models.CharField(max_length=20)),
                ('datum', models.DateTimeField()),
                ('tip', models.CharField(choices=[('KEŠ', 'Keš'), ('Kart', 'Kartica'), ('Paypal', 'PayPal')], default='Keš', max_length=20)),
            ],
        ),
    ]
