# Generated by Django 2.2.10 on 2020-05-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner_ukupno_dug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='ukupno_dug',
            new_name='iznos',
        ),
    ]
