# Generated by Django 2.2.10 on 2020-06-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transakcije'),
    ]

    operations = [
        migrations.CreateModel(
            name='DugNas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='dugovanje',
            new_name='dugovanje_prema',
        ),
        migrations.AddField(
            model_name='partner',
            name='dugovanje_od',
            field=models.ManyToManyField(blank=True, null=True, to='core.DugNas'),
        ),
    ]
