# Generated by Django 2.2.10 on 2020-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200601_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='iznos',
            new_name='iznos_od',
        ),
        migrations.AddField(
            model_name='partner',
            name='iznos_prema',
            field=models.FloatField(default=0.0),
        ),
    ]
