# Generated by Django 2.2.10 on 2020-05-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nabavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nabavka',
            name='racuni',
            field=models.ManyToManyField(to='core.ulazni_rac'),
        ),
    ]
