# Generated by Django 2.2.10 on 2020-06-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200601_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiva', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('pasiva', models.CharField(max_length=100)),
                ('izlazni_racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.izlazni_rac')),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Konto')),
                ('ulazni_racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ulazni_rac')),
            ],
        ),
    ]
