# Generated by Django 2.2.10 on 2020-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bilans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilans',
            name='aktiva',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bilans',
            name='pasiva',
            field=models.FloatField(max_length=100),
        ),
    ]
