# Generated by Django 2.2.10 on 2020-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200523_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nabavka',
            name='racuni',
            field=models.ManyToManyField(to='core.Racun'),
        ),
    ]
