# Generated by Django 2.2.10 on 2020-05-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200523_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='nabavka',
            name='iznos',
            field=models.FloatField(default=0.0),
        ),
    ]
