# Generated by Django 2.2.10 on 2020-06-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200601_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilans',
            name='aktiva',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bilans',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilans',
            name='izlazni_racun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.izlazni_rac'),
        ),
        migrations.AlterField(
            model_name='bilans',
            name='konto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Konto'),
        ),
        migrations.AlterField(
            model_name='bilans',
            name='pasiva',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bilans',
            name='ulazni_racun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ulazni_rac'),
        ),
    ]
