from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Artikal)
admin.site.register(Kategorija)
admin.site.register(Asortiman)
admin.site.register(Racun)
admin.site.register(ulazni_rac)
admin.site.register(izlazni_rac)
admin.site.register(Partner)
admin.site.register(Ugovor)
admin.site.register(Usluga)
admin.site.register(Budzet)
admin.site.register(Avans)
admin.site.register(Konto)
admin.site.register(DugPartner)
admin.site.register(Nabavka)
admin.site.register(User)
admin.site.register(Obavijesti)
admin.site.register(Projekti)
admin.site.register(Tenderi)
admin.site.register(Blagajna)
admin.site.register(Transakcije)
admin.site.register(DugNas)
admin.site.register(Bilans)
